<a href="https://colab.research.google.com/github/rociotarda/TP1---Datos/blob/main/DataSetTP1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from google.colab import files
uploaded = files.upload()

Saving train_labels.csv to train_labels.csv
Saving train_values.csv to train_values.csv

In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import io
  
train_labels = pd.read_csv(io.BytesIO(uploaded['train_labels.csv']))
train_labels.head()

   building_id  damage_grade
0       802906             3
1        28830             2
2        94947             3
3       590882             2
4       201944             3

In [8]:
train_values = pd.read_csv(io.BytesIO(uploaded['train_values.csv']))
train_values.head()

   building_id  ...  has_secondary_use_other
0       802906  ...                        0
1        28830  ...                        0
2        94947  ...                        0
3       590882  ...                        0
4       201944  ...                        0

[5 rows x 39 columns]